-- ============================================================
-- Kullanıcı ve yetki tabloları
-- Her kullanıcının hangi scope'lara erişebileceği burada tanımlanır
-- ============================================================

CREATE TABLE app_users (
    id        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  VARCHAR(50)  NOT NULL UNIQUE,
    password  VARCHAR(200) NOT NULL,
    enabled   BOOLEAN      NOT NULL DEFAULT TRUE,
    email     VARCHAR(100),
    full_name VARCHAR(100)
);

-- Her kullanıcının sahip olduğu grant'lar / scope'lar
-- Örn: SCOPE_read, SCOPE_write, ROLE_ADMIN
CREATE TABLE user_grants (
    user_id   BIGINT       NOT NULL,
    authority VARCHAR(100) NOT NULL,
    PRIMARY KEY (user_id, authority),
    FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE
);

