CREATE TABLE acs_transactions (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id        VARCHAR(100) NOT NULL UNIQUE,
    payment_id            BIGINT,
    payment_callback_url  VARCHAR(500),
    frontend_callback_url VARCHAR(500),
    amount                VARCHAR(50),
    merchant_name         VARCHAR(200),
    status                VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    attempts              INT DEFAULT 0,
    created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at            TIMESTAMP
);

