CREATE TABLE user_profiles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    VARCHAR(200) NOT NULL UNIQUE,
    username   VARCHAR(100) NOT NULL,
    email      VARCHAR(150),
    full_name  VARCHAR(150),
    bio        VARCHAR(500),
    avatar_url VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

