CREATE TABLE cart_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       VARCHAR(200)   NOT NULL,
    product_id    BIGINT         NOT NULL,
    product_name  VARCHAR(300),
    product_price DECIMAL(12, 2),
    quantity      INT            NOT NULL DEFAULT 1,
    added_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_cart_user_product UNIQUE (user_id, product_id)
);

